#!/usr/bin/env python
"""Compose the per-worker-type instruction files from shared blocks in worker_src/.

EVERY WORKER READS EXACTLY ONE FILE, and that file contains only what that worker type needs. A worker
doc is a PER-INVOCATION cost — 12 workers/wave means every KB is ~3k tokens/wave — so a small-overlay
worker must not pay for the `main` delta or the large-function delta it will never use.

Composed, not forked. Editing a recipe means editing worker_src/core.md once; every variant picks it up
on the next build. (Forking these files is what let five copies drift apart until their ARM-vs-THUMB
assumptions silently dropped 28 of 31 gate-verified matches — never hand-edit the built files.)

  worker_ov.md        overlay, <=256B   core
  worker_ovL.md       overlay, >256B    core + large
  worker_main.md      main,    <=256B   core + main
  worker_mainL.md     main,    >256B    core + main + large

Usage: python build_worker_docs.py   (run_overlay.sh/run_main.sh call it before spawning a wave)
"""
import os as _kpos, sys as _kpsys
_kpsys.path.insert(0, _kpos.path.dirname(_kpos.path.abspath(__file__)))
import kitpaths as _kp
import io, os, sys

SP = _kp.SP
SRC = f"{SP}/worker_src"

BANNER = ("<!-- GENERATED by build_worker_docs.py from worker_src/. DO NOT EDIT THIS FILE — "
          "edit worker_src/*.md and rebuild, or your change is lost on the next wave. -->\n")


def read(n, required=True):
    # A MISSING DELTA IS NOT A REASON TO PRODUCE NOTHING. worker_src/ lost delta_main.md and
    # delta_large.md, and run_module discards this script's output, so a crash here left every
    # worker_*.md frozen at whatever was on disk weeks earlier while looking generated.
    try:
        return io.open(f"{SRC}/{n}", encoding='utf-8').read().rstrip() + "\n"
    except OSError:
        if required:
            raise
        sys.stderr.write("WARN %s is missing; building without it\n" % n)
        return ""


core = read("core.md")
dmain = read("delta_main.md", required=False)
dlarge = read("delta_large.md", required=False)

VARIANTS = {
    "worker_ov.md":    [core],
    "worker_ovL.md":   [core, dlarge],
    "worker_main.md":  [core, dmain],
    "worker_mainL.md": [core, dmain, dlarge],
}

# RESIDENT vs ON-DEMAND. The assembled doc was ~24,400 tokens and every worker session read all of
# it, but only the procedural part is needed before the first gate run -- the rest is 45+ situational
# recipes, of which a session consults two or three. At 264 sessions in the measured week that is
# roughly 5.7M input tokens of recipes nobody opened.
#
# Sections named below stay in the doc. EVERYTHING ELSE moves to worker_recipes.md, and the doc gets
# a one-line index instead. Unknown headings default to RESIDENT deliberately: adding a section to
# core.md must never silently remove it from what workers read, so moving one out is an explicit act.
RESIDENT = [
    "Paths", "CONTEXT BUDGET", "GATE", "Bans", "Loop per ADDR", "Relocs",
    "Same encoding", "Struct copy", "Reference kinds", "Signatures", "Final .cpp",
    "BYTEDIFF", "IF THAT FAILS", "VERDICT", "Output",
]

# OFF BY DEFAULT, because measurement said so. Splitting recipes out cut the doc from ~24k to ~5.4k
# tokens and looked like a clear win -- but of the first 55 sessions that ran under it, ZERO called
# recipe.py or opened the recipes file. Telling a worker that a reference exists is not the same as
# it reading one, so in practice the split deleted 21k tokens of matching knowledge rather than
# deferring it, and the large band went 0-for-5 (~$11 spent, nothing landed) against a 49% historical
# conversion. Match rate dominates $/function; token count does not. Re-enable only with a prompt
# that forces a fetch and a check that uptake actually happened.
SPLIT_RECIPES = os.environ.get("SPLIT_RECIPES", "0") == "1"


def split_sections(text):
    """(resident_text, [(heading, body)]) -- headings matched by prefix against RESIDENT."""
    parts = re.split(r"(?m)^(## .*)$", text)
    head, out, recipes = parts[0], [parts[0]], []
    for i in range(1, len(parts), 2):
        heading, body = parts[i], parts[i + 1] if i + 1 < len(parts) else ""
        title = heading[3:].strip()
        if any(title.startswith(k) for k in RESIDENT):
            out.append(heading + body)
        else:
            recipes.append((title, heading + body))
    return "".join(out), recipes


for name, parts in VARIANTS.items():
    full = BANNER + "\n".join(p.rstrip() + "\n" for p in parts)
    resident, recipes = split_sections(full) if SPLIT_RECIPES else (full, [])
    rname = name.replace(".md", "_recipes.md")
    if recipes:
        index = ["", "## RECIPE INDEX — fetch on demand, do NOT read this file whole", "",
                 f"The recipes live in `{SP}/{rname}`. When the gate reports a BYTEDIFF you cannot",
                 "place, find the matching title below and read THAT SECTION ONLY, e.g.:",
                 f"`python {SP}/recipe.py {rname} \"<title>\"`. Reading all of them costs ~21k tokens",
                 "and a session needs two or three.", ""]
        index += [f"- {t}" for t, _ in recipes]
        resident = resident.rstrip() + "\n" + "\n".join(index) + "\n"
        io.open(f"{SP}/{rname}", 'w', encoding='utf-8').write(
            "".join(b for _t, b in recipes))
    p = f"{SP}/{name}"
    old = io.open(p, encoding='utf-8').read() if os.path.exists(p) else None
    if old != resident:
        io.open(p, 'w', encoding='utf-8').write(resident)
    print(f"{name:17s} {len(resident):6d} B (~{len(resident)//4} tok) "
          f"+ {len(recipes)} recipes on demand")
